version: '3.8'
services:
  # app:
  #   container_name: apollo-server
  #   build:
  #     context: ../
  #     dockerfile: ../Dockerfile
  #   ports:
  #     - 4000:4000
  #     - 5555:5555
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ../.env
  postgres:
    image: postgres:10.3
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=eringiv3
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
